export const customizebynameData=[
    {
        mainImage: "images/name1.jpg",
        carouselImages: ["images/name1.jpg", "images/name2.jpg", "images/name3.jpg","images/name4.jpg"],
        plannername:"Customized Name Notebook[200 Pages]",
        numPage: ['200 Pages','300 Pages', '400 Pages','Pack of 2,200 Pages','Pack of 3, 300 Pages','Pack of 2, 400 Pages','Pack of 3, 200 Pages','Pack of 3, 300 Pages','Pack of 3, 400 Pages','Pack of 6, 200 Pages','Pack of 6, 300 Pages','Pack of 6, 400 Pages',],
        mainprice:['Rs.149.00', "Rs.174.00", "Rs.199.00","Rs.289.00", "Rs.339.00","Rs.389.00", "Rs.420.00","Rs.499.00", "Rs.577.00", "Rs.799.00","Rs.959.00", "Rs.1111.00",],
        preprice:['Rs.149.00', "Rs.299.00", "Rs.0.00","Rs.399.00", "Rs.599.00","Rs.799.00", "Rs.599.00","Rs.899.00", "Rs.1199.00", "Rs.1299.00","Rs.1799.00", "Rs.2399.00",],
        saveprice:['Rs.149.00', "Rs.125.00", "Rs.199.00","Rs.110.00", "Rs.260.00","Rs.410.00", "Rs.179.00","Rs.400.00", "Rs.622.00", "Rs.500.00","Rs.840.00", "Rs.1288.00",],
        description: "A4 Spiral Bound Notebook,200 Pages,29*21cm, Unruled(Customized Name Notebooks)",
        description2:".Brand:The Print Station",
        description3:".Size:A4,29.7*21 cm",
        description4:".Ruling:Plain",
        description5:".Cover Finish:Photo Glossy",
        description6:".Paper Finish:Uncoated",
        description7:".GSM:70", 
      

    },
    {
        mainImage: "images/name5.jpg",
        carouselImages: ["images/name5.jpg", "images/name6.jpg", "images/name7.jpg","images/name8.jpg"],
        plannername:"Customized Name Notebook[200 Pages]",
        mainprice:"Rs.149.00",
        preprice:"Rs.199.00",
        saveprice:"Save Rs.50.00",
        description: "A4 Spiral Bound Notebook,200 Pages,29*21cm, Unruled(Customized Name Notebooks)",
        description2:".Brand:The Print Station",
        description3:".Size:A4,29.7*21 cm",
        description4:".Ruling:Plain",
        description5:".Cover Finish:Photo Glossy",
        description6:".Paper Finish:Uncoated",
        description7:".GSM:70", 
      

    },
    {
        mainImage: "images/name9.jpg",
        carouselImages: ["images/name9.jpg", "images/name10.jpg", "images/name11.jpg","images/name12.jpg"],
        plannername:"Customized Name Notebook[200 Pages]",
        mainprice:"Rs.149.00",
        preprice:"Rs.199.00",
        saveprice:"Save Rs.50.00",
        description: "A4 Spiral Bound Notebook,200 Pages,29*21cm, Unruled(Customized Name Notebooks)",
        description2:".Brand:The Print Station",
        description3:".Size:A4,29.7*21 cm",
        description4:".Ruling:Plain",
        description5:".Cover Finish:Photo Glossy",
        description6:".Paper Finish:Uncoated",
        description7:".GSM:70", 
      

    },
    {
        mainImage: "images/name13.jpg",
        carouselImages: ["images/name13.jpg", "images/name14.jpg", "images/name15.jpg","images/name16.jpg"],
        plannername:"Customized Name Notebook[200 Pages]",
        mainprice:"Rs.149.00",
        preprice:"Rs.199.00",
        saveprice:"Save Rs.50.00",
        description: "A4 Spiral Bound Notebook,200 Pages,29*21cm, Unruled(Customized Name Notebooks)",
        description2:".Brand:The Print Station",
        description3:".Size:A4,29.7*21 cm",
        description4:".Ruling:Plain",
        description5:".Cover Finish:Photo Glossy",
        description6:".Paper Finish:Uncoated",
        description7:".GSM:70", 
      

    },
    {
        mainImage: "images/name17.jpg",
        carouselImages: ["images/name17.jpg", "images/name18.jpg", "images/name19.jpg","images/name20.jpg"],
        plannername:"Customized Name Notebook[200 Pages]",
        mainprice:"Rs.149.00",
        preprice:"Rs.199.00",
        saveprice:"Save Rs.50.00",
        description: "A4 Spiral Bound Notebook,200 Pages,29*21cm, Unruled(Customized Name Notebooks)",
        description2:".Brand:The Print Station",
        description3:".Size:A4,29.7*21 cm",
        description4:".Ruling:Plain",
        description5:".Cover Finish:Photo Glossy",
        description6:".Paper Finish:Uncoated",
        description7:".GSM:70", 
      

    },
    {
        mainImage: "images/name21.jpg",
        carouselImages: ["images/name21.jpg", "images/name22.jpg", "images/name23.jpg","images/name24.jpg"],
        plannername:"Customized Name Notebook[200 Pages]",
        mainprice:"Rs.149.00",
        preprice:"Rs.199.00",
        saveprice:"Save Rs.50.00",
        description: "A4 Spiral Bound Notebook,200 Pages,29*21cm, Unruled(Customized Name Notebooks)",
        description2:".Brand:The Print Station",
        description3:".Size:A4,29.7*21 cm",
        description4:".Ruling:Plain",
        description5:".Cover Finish:Photo Glossy",
        description6:".Paper Finish:Uncoated",
        description7:".GSM:70", 
      

    },
    {
        mainImage: "images/name25.jpg",
        carouselImages: ["images/name25.jpg", "images/name26.jpg", "images/name27.jpg","images/name28.jpg"],
        plannername:"Customized Name Notebook[200 Pages]",
        mainprice:"Rs.149.00",
        preprice:"Rs.199.00",
        saveprice:"Save Rs.50.00",
        description: "A4 Spiral Bound Notebook,200 Pages,29*21cm, Unruled(Customized Name Notebooks)",
        description2:".Brand:The Print Station",
        description3:".Size:A4,29.7*21 cm",
        description4:".Ruling:Plain",
        description5:".Cover Finish:Photo Glossy",
        description6:".Paper Finish:Uncoated",
        description7:".GSM:70", 
      

    },
]