export const diaryData=[
    {
        mainImage: "images/d1.jpg",
        carouselImages: ["images/d1.jpg", "images/d2.jpg", "images/d3.jpg"],
        plannername:"Diary 74",
        mainprice:"Rs.249.00",
        preprice:"Rs.499.00",
        saveprice:"Save Rs.250.00",
        description: "Diary 74,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
      
    },
    {
        mainImage: "images/d4.jpg",
        carouselImages: ["images/d4.jpg","images/d5.jpg", "images/d6.jpg", "images/d7.jpg"],
        plannername:"Diary 125",
        mainprice:"Rs.299.00",
        preprice:"Rs.599.00",
        saveprice:"Save Rs.300.00",
        description: "Diary 125,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },
    {
        mainImage: "images/d8.jpg",
        carouselImages: ["images/d8.jpg", "images/d9.jpg", "images/d10.jpg", "images/d11.jpg"],
        plannername:"Diary 126",
        mainprice:"Rs.299.00",
        preprice:"Rs.599.00",
        saveprice:"Save Rs.300.00",
        description: "Diary 126,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },
    {
        mainImage: "images/d12.jpg",
        carouselImages:["images/d12.jpg", "images/d13.jpg", "images/d14.jpg", "images/d15.jpg"],
        plannername:"Diary 127",
        mainprice:"Rs.299.00",
        preprice:"Rs.599.00",
        saveprice:"Save Rs.300.00",
        description: "Diary 127,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },
    {
        mainImage: "images/d16.jpg",
        carouselImages: ["images/d16.jpg", "images/d17.jpg", "images/d18.jpg", "images/d19.jpg"],
        plannername:"Diary 128",
        mainprice:"Rs.299.00",
        preprice:"Rs.599.00",
        saveprice:"Save Rs.300.00",
        description: "Diary 128,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },
    {
        mainImage: "images/d20.jpg",
        carouselImages:["images/d20.jpg", "images/d21.jpg", "images/d22.jpg", "images/d23.jpg","images/d24.jpg"],
        plannername:"Diary 129",
        mainprice:"Rs.299.00",
        preprice:"Rs.599.00",
        saveprice:"Save Rs.300.00",
        description: "Diary 129,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },
    {
        mainImage: "images/d25.jpg",
        carouselImages: ["images/d25.jpg", "images/d26.jpg", "images/d27.jpg", "images/d28.jpg"],
        plannername:"Diary 205",
        mainprice:"Rs.499.00",
        preprice:"Rs.999.00",
        saveprice:"Save Rs.550.00",
        description: "Diary 205,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth", 
    },
    {
        mainImage: "images/d29.jpg",
        carouselImages:["images/d29.jpg", "images/d30.jpg", "images/d31.jpg", "images/d32.jpg"],
        plannername:"Diary 216",
        mainprice:"Rs.399.00",
        preprice:"Rs.999.00",
        saveprice:"Save Rs.600.00",
        description: "Diary 129,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },  
    
    
    {
        mainImage: "images/d33.jpg",
        carouselImages: ["images/d33.jpg", "images/d34.jpg", "images/d35.jpg", "images/d36.jpg"],
        plannername:"Diary 229",
        mainprice:"Rs.399.00",
        preprice:"Rs.899.00",
        saveprice:"Save Rs.500.00",
        description: "Diary 229,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },
    {
        mainImage: "images/d37.jpg",
        carouselImages:["images/d37.jpg", "images/d38.jpg", "images/d39.jpg", "images/d40.jpg"],
        plannername:"Diary 4320",
        mainprice:"Rs.249.00",
        preprice:"Rs.599.00",
        saveprice:"Save Rs.350.00",
        description: "Diary 4320,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    }, 
    
    
    {
        mainImage: "images/d41.jpg",
        carouselImages: ["images/d41.jpg", "images/d42.jpg", "images/d43.jpg", "images/d44.jpg","images/d45.jpg","images/d46.jpg"],
        plannername:"Folder Diary 5005",
        mainprice:"Rs.849.00",
        preprice:"Rs.1499.00",
        saveprice:"Save Rs.650.00",
        description: "Diary 129,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },
    {
        mainImage: "images/d47.jpg",
        carouselImages:["images/d47.jpg", "images/d48.jpg", "images/d49.jpg", "images/d50.jpg"],
        plannername:"Organiser 000",
        mainprice:"Rs.499.00",
        preprice:"Rs.999.00",
        saveprice:"Save Rs.550.00",
        description: "Organiser 000,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    }, 
    
    {
        mainImage: "images/d51.jpg",
        carouselImages: ["images/d51.jpg", "images/d52.jpg", "images/d53.jpg", "images/d54.jpg"],
        plannername:"Organiser 106",
        mainprice:"Rs.699.00",
        preprice:"Rs.1299.00",
        saveprice:"Save Rs.600.00",
        description: "Organiser 106,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },

    {
        mainImage: "images/d55.jpg",
        carouselImages:["images/d55.jpg", "images/d56.jpg", "images/d57.jpg", "images/d58.jpg"],
        plannername:"Organiser 109",
        mainprice:"Rs.649.00",
        preprice:"Rs.1299.00",
        saveprice:"Save Rs.650.00",
        description: "Organiser 109,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth", 
    }, 
    
    {
        mainImage: "images/d59.jpg",
        carouselImages:["images/d59.jpg", "images/d60.jpg", "images/d61.jpg", "images/d62.jpg"],
        plannername:"Organiser 119",
        mainprice:"Rs.599.00",
        preprice:"Rs.1199.00",
        saveprice:"Save Rs.600.00",
        description: "Organiser 119,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    },
    {
        mainImage: "images/d63.jpg",
        carouselImages:["images/d63.jpg", "images/d64.jpg", "images/d65.jpg", "images/d66.jpg"],
        plannername:"Organiser Well",
        mainprice:"Rs.469.00",
        preprice:"Rs.1099.00",
        saveprice:"Save Rs.630.00",
        description: "Organiser Well,High Quality PU Leather, Planner/Daily 2022 ",
        description2:".Cover Material:Faux Leather",
        description3:".Use:Office/Personal/Gifting",
        description4:".Paper finish:Smooth",
    }
    ]