export const motivationalquoteframewithpostersData=[
    {
        mainImage: "images/MQ1.jpg",
        carouselImages: ["images/MQ1.jpg", "images/MQ2.jpg", "images/MQ3.jpg", "images/MQ4.jpg"],
        plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Design 1)",
        mainprice:"Rs.299.00",
        preprice:"Rs.999.00",
        saveprice:"Save Rs.700.00",
        description: "Explore the Purposeful & Motivational Picture frames from THE PRINT STATION",
        description2:".Brand:The Print Station",
        description3:".Size:13.2*9.7 inch",
        description4:".Colour:Multi",
        description5:".Material:Synthetic wood,Gloss Paper,Laminated",
        description6:".Theme:Motivational",
        description7:".Size/Shape:A4", 
        description8:".Frame type:Framed", 
        description9:".Paint:Digital High Quality", 

    },
    {
        mainImage: "images/MQ5.jpg",
        carouselImages: ["images/MQ5.jpg", "images/MQ6.jpg", "images/MQ7.jpg", "images/MQ8.jpg"],
        plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 1)",
        mainprice:"Rs.299.00",
        preprice:"Rs.999.00",
        saveprice:"Save Rs.700.00",
        description: "Explore the Purposeful & Motivational Picture frames from THE PRINT STATION",
        description2:".Brand:The Print Station",
        description3:".Size:13.2*9.7 inch",
        description4:".Colour:Multi",
        description5:".Material:Synthetic wood,Gloss Paper,Laminated",
        description6:".Theme:Motivational",
        description7:".Size/Shape:A4", 
        description8:".Frame type:Framed", 
        description9:".Paint:Digital High Quality", 
    },

{
    mainImage: "images/MQ9.jpg",
    carouselImages: ["images/MQ9.jpg", "images/MQ10.jpg", "images/MQ11.jpg", "images/MQ12.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 1)",
    mainprice:"Rs.299.00",
    preprice:"Rs.999.00",
    saveprice:"Save Rs.700.00",
    description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
    description2:".Brand:The Print Station",
    description3:".Size:13.2*9.7 inch",
    description4:".Colour:Multi",
    description5:".Material:Synthetic wood,Gloss Paper,Laminated",
    description6:".Theme:Motivational",
    description7:".Size/Shape:A4", 
    description8:".Frame type:Framed", 
    description9:".Paint:Digital High Quality", 
},
{
    mainImage: "images/MQ13.jpg",
    carouselImages: ["images/MQ13.jpg", "images/MQ14.jpg", "images/MQ15.jpg", "images/MQ16.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 1)",
    mainprice:"Rs.299.00",
    preprice:"Rs.999.00",
    saveprice:"Save Rs.700.00",
    description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
    description2:".Brand:The Print Station",
    description3:".Size:13.2*9.7 inch",
    description4:".Colour:Multi",
    description5:".Material:Synthetic wood,Gloss Paper,Laminated",
    description6:".Theme:Motivational",
    description7:".Size/Shape:A4", 
    description8:".Frame type:Framed", 
    description9:".Paint:Digital High Quality", 
}
,
{
    mainImage: "images/MQ17.jpg",
    carouselImages: ["images/MQ17.jpg", "images/MQ18.jpg", "images/MQ19.jpg", "images/MQ20.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 1)",
    mainprice:"Rs.299.00",
    preprice:"Rs.999.00",
    saveprice:"Save Rs.700.00",
    description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
    description2:".Brand:The Print Station",
    description3:".Size:13.2*9.7 inch",
    description4:".Colour:Multi",
    description5:".Material:Synthetic wood,Gloss Paper,Laminated",
    description6:".Theme:Motivational",
    description7:".Size/Shape:A4", 
    description8:".Frame type:Framed", 
    description9:".Paint:Digital High Quality", 
}
,
{
    mainImage: "images/MQ21.jpg",
    carouselImages: ["images/MQ21.jpg", "images/MQ22.jpg", "images/MQ23.jpg", "images/MQ24.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 1)",
    mainprice:"Rs.299.00",
    preprice:"Rs.999.00",
    saveprice:"Save Rs.700.00",
    description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
    description2:".Brand:The Print Station",
    description3:".Size:13.2*9.7 inch",
    description4:".Colour:Multi",
    description5:".Material:Synthetic wood,Gloss Paper,Laminated",
    description6:".Theme:Motivational",
    description7:".Size/Shape:A4", 
    description8:".Frame type:Framed", 
    description9:".Paint:Digital High Quality", 
}
,
{
    mainImage: "images/MQ25.jpg",
    carouselImages: ["images/MQ25.jpg", "images/MQ26.jpg", "images/MQ27.jpg", "images/MQ28.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 1)",
    mainprice:"Rs.299.00",
    preprice:"Rs.999.00",
    saveprice:"Save Rs.700.00",
    description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
    description2:".Brand:The Print Station",
    description3:".Size:13.2*9.7 inch",
    description4:".Colour:Multi",
    description5:".Material:Synthetic wood,Gloss Paper,Laminated",
    description6:".Theme:Motivational",
    description7:".Size/Shape:A4", 
    description8:".Frame type:Framed", 
    description9:".Paint:Digital High Quality", 
}
,
{
    mainImage: "images/MQ29.jpg",
    carouselImages: ["images/MQ29.jpg", "images/MQ30.jpg", "images/MQ31.jpg", "images/MQ32.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 2)",
    mainprice:"Rs.549.00",
    preprice:"Rs.1399.00",
    saveprice:"Save Rs.850.00",
    description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
    description2:".Brand:The Print Station",
    description3:".Size:13.2*9.7 inch",
    description4:".Colour:Multi",
    description5:".Material:Synthetic wood,Gloss Paper,Laminated",
    description6:".Theme:Motivational",
    description7:".Size/Shape:A4", 
    description8:".Frame type:Framed", 
    description9:".Paint:Digital High Quality", 
}
,
{
    mainImage: "images/MQ33.jpg",
    carouselImages: ["images/MQ33.jpg", "images/MQ34.jpg", "images/MQ35.jpg", "images/MQ36.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 3)",
    mainprice:"Rs.799.00",
    preprice:"Rs.1699.00",
    saveprice:"Save Rs.900.00",
    description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
    description2:".Brand:The Print Station",
    description3:".Size:13.2*9.7 inch",
    description4:".Colour:Multi",
    description5:".Material:Synthetic wood,Gloss Paper,Laminated",
    description6:".Theme:Motivational",
    description7:".Size/Shape:A4", 
    description8:".Frame type:Framed", 
    description9:".Paint:Digital High Quality", 
}
,
{
    mainImage: "images/MQ37.jpg",
    carouselImages: ["images/MQ37.jpg", "images/MQ38.jpg", "images/MQ39.jpg", "images/MQ40.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 4)",
        mainprice:"Rs.999.00",
        preprice:"Rs.1999.00",
        saveprice:"Save Rs.1000.00",
        description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
        description2:".Brand:The Print Station",
        description3:".Size:13.2*9.7 inch",
        description4:".Colour:Multi",
        description5:".Material:Synthetic wood,Gloss Paper,Laminated",
        description6:".Theme:Motivational",
        description7:".Size/Shape:A4", 
        description8:".Frame type:Framed", 
        description9:".Paint:Digital High Quality", 
}
,
{
    mainImage: "images/MQ41.jpg",
    carouselImages: ["images/MQ41.jpg", "images/MQ42.jpg", "images/MQ43.jpg", "images/MQ44.jpg"],
    plannername:"TPS Motivational Quotes wall Frames Art,Digital Redprint Posters with Synthetic wooden frame(Set of 6)",
        mainprice:"Rs.1499.00",
        preprice:"Rs.3999.00",
        saveprice:"Save Rs.2550.00",
        description: "Explore the Purpose & Motivational Picture frames from THE PRINT STATION",
        description2:".Brand:The Print Station",
        description3:".Size:13.2*9.7 inch",
        description4:".Colour:Multi",
        description5:".Material:Synthetic wood,Gloss Paper,Laminated",
        description6:".Theme:Motivational",
        description7:".Size/Shape:A4", 
        description8:".Frame type:Framed", 
        description9:".Paint:Digital High Quality", 
}

]