export const motivationalpostersData=[
    {
        mainImage: "images/M1.jpg",
        carouselImages: ["images/M1.jpg", "images/M2.jpg", "images/M3.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M4.jpg",
        carouselImages: ["images/M4.jpg", "images/M5.jpg", "images/M6.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M7.jpg",
        carouselImages: ["images/M7.jpg", "images/M8.jpg", "images/M9.jpg",],
         plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M10.jpg",
        carouselImages:["images/M10.jpg", "images/M11.jpg", "images/M12.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M13.jpg",
        carouselImages:["images/M13.jpg", "images/M14.jpg", "images/M15.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M16.jpg",
        carouselImages:["images/M16.jpg", "images/M17.jpg", "images/M18.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M19.jpg",
        carouselImages:["images/M19.jpg", "images/M20.jpg", "images/M21.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M22.jpg",
        carouselImages:["images/M22.jpg","images/M23.jpg", "images/M24.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M25.jpg",
        carouselImages:["images/M25.jpg", "images/M26.jpg", "images/M27.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1",  
    },
    {
        mainImage: "images/M28.jpg",
        carouselImages:["images/M28.jpg", "images/M29.jpg", "images/M30.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M31.jpg",
        carouselImages:["images/M31.jpg", "images/M32.jpg", "images/M33.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
        
    },
 
    {
        mainImage: "images/M34.jpg",
        carouselImages:["images/M34.jpg", "images/M35.jpg", "images/M36.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    }

    ,
    {
        mainImage: "images/M37.jpg",
        carouselImages:["images/M37.jpg", "images/M38.jpg", "images/M39.jpg"],
        description: "",
        price: 123, 
    }
    ,
    {
        mainImage: "images/M40.jpg",
        carouselImages:["images/M40.jpg", "images/M41.jpg", "images/M42.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1",  
    }
    ,
    {
        mainImage: "images/M43.jpg",
        carouselImages:["images/M43.jpg", "images/M44.jpg", "images/M45.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    }
    ,
    {
        mainImage: "images/M46.jpg",
        carouselImages:["images/M46.jpg", "images/M47.jpg", "images/M48.jpg"],
        description: "",
        price: 123, 
    }
    ,
    {
        mainImage: "images/M49.jpg",
        carouselImages:["images/M49.jpg", "images/M50.jpg", "images/M51.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    },
    {
        mainImage: "images/M52.jpg",
        carouselImages:["images/M52.jpg", "images/M53.jpg", "images/M54.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1",  
    }
    ,
    {
        mainImage: "images/M55.jpg",
        carouselImages:["images/M55.jpg", "images/M56.jpg", "images/M57.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1",  
    }
    ,
    {
        mainImage: "images/M58.jpg",
        carouselImages:["images/M58.jpg", "images/M59.jpg", "images/M60.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    }
    ,
    {
        mainImage: "images/M61.jpg",
        carouselImages:["images/M61.jpg", "images/M62.jpg", "images/M63.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    }
    ,
 
    {
        mainImage: "images/M64.jpg",
        carouselImages:["images/M64.jpg", "images/M65.jpg", "images/M66.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1",  
    }
    ,
    {
        mainImage: "images/M67.jpg",
        carouselImages:["images/M67.jpg", "images/M68.jpg", "images/M69.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    }
    ,
    {
        mainImage: "images/M70.jpg",
        carouselImages:["images/M70.jpg", "images/M71.jpg", "images/M72.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1",  
    }
    ,
    {
        mainImage: "images/M73.jpg",
        carouselImages:["images/M73.jpg", "images/M74.jpg", "images/M75.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    }
    ,
    {
        mainImage: "images/M76.jpg",
        carouselImages:["images/M76.jpg", "images/M77.jpg", "images/M78.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    }
    ,
    {
        mainImage: "images/M79.jpg",
        carouselImages:["images/M79.jpg", "images/M80.jpg", "images/M81.jpg"],
        plannername:"HD Wall Poster ,300 GSM Glossy Paper With Glass Laminated (Multicolor),Packet 0f 1",
        mainprice:"Rs.99.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.300.00",
        description: "Free Delivery Just Above Rs.199",
        description2:".Brand:The Print Station",
        description3:".Size:A4,8.3*11.7 inch",
        description4:".Material:Glossy Paper",
        description5:".Theme:Motivational Quote",
        description6:".Frame Type:Unframed", 
        description7:".No. of Pieces:1", 
    }


]

