export const plannerData=[
    {
        mainImage: "images/1.jpg",
        carouselImages: ["images/1.jpg", "images/2.jpg", "images/3.jpg"],
        plannername:"365 Days Planner With Health Checklist",
        mainprice:"Rs.199.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.200.00",
        description: "365 Days/Yearly Daily Planner, 365 Pages,Size A5, A planner for Every Day of the Year,Spiral Bounded",
        description2:".Brand:The Print Station",
        description3:".Size:A5",
        description4:".Binding:Spiral Bound",
        description5:".Cover:Glossy",
        description6:".Pages:365",
        description7:".Paper:70 GSM",
      
    },
    {
        mainImage: "images/4.jpg",
        carouselImages: ["images/4.jpg", "images/5.jpg", "images/6.jpg"],
        plannername:"Daily Planner With Priority List",
        mainprice:"Rs.199.00",
        preprice:"Rs.399.00",
        saveprice:"Save Rs.200.00",
        description: "365 Days/Yearly Daily Planner, 365 Pages,Size A5, A planner for Every Day of the Year,Spiral Bounded",
        description2:".Brand:The Print Station",
        description3:".Size:A5",
        description4:".Binding:Spiral Bound",
        description5:".Cover:Glossy",
        description6:".Pages:365",
        description7:".Paper:70 GSM",
    },
    {
        mainImage: "images/7.jpg",
        carouselImages: ["images/7.jpg", "images/8.jpg", "images/9.jpg", "images/10.jpg"],
        plannername:"Planner 9009",
        mainprice:"Rs.569.00",
        preprice:"Rs.1099.00",
        saveprice:"Save Rs.530.00",
        description: "365 Days/Yearly Daily Planner, 365 Pages,Size A5, A planner for Every Day of the Year,Spiral Bounded",
        description2:".Brand:The Print Station",
        description3:".Size:A5",
        description4:".Binding:Spiral Bound",
        description5:".Cover:Glossy",
        description6:".Pages:365",
        description7:".Paper:70 GSM",
    },
    {
        mainImage: "images/11.jpg",
        carouselImages:["images/11.jpg", "images/12.jpg", "images/13.jpg", "images/14.jpg"],
        plannername:"Planner 9012",
        mainprice:"Rs.599.00",
        preprice:"Rs.1499.00",
        saveprice:"Save Rs.900.00",
        description: "365 Days/Yearly Daily Planner, 365 Pages,Size A5, A planner for Every Day of the Year,Spiral Bounded",
        description2:".Brand:The Print Station",
        description3:".Size:A5",
        description4:".Binding:Spiral Bound",
        description5:".Cover:Glossy",
        description6:".Pages:365",
        description7:".Paper:70 GSM",
    }
]